### DISCUSSION TITLE
🔗 Offset Slides for the Image Carousel (Same as Nested and Loop Carousel)

### DISCUSSION THREAD

**Discussion by benoitfouc** [elementor/elementor#23337] [Feature Request]
### Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro )

### What problem is your feature request going to solve? Please describe.

There is a new feature name "Offset slides" for Carousel and Loop carousel. This feature is missing for the "image carousel" widget.

It's a visual feature that broke

### Describe the solution you'd like

Offsetting carousel slides will spark your visitors’ curiosity by showing them part of the next slides on either side of the carousel. You can offset either side of your carousel to boost engagement and help indicate that there’s additional content still to come.

**Comment by nolderoos** [comment]
Hi there,

We were looking for the same feature.

We managed to achieve it with some simple CSS, though I agree it would be great if this were part of Elementor Core:

```css
selector {
    overflow: visible; /* Allow overflow to show the bleeding edge */
}

.elementor-image-carousel-wrapper {
    padding-right: 30px; /* Create space for the bleeding edge */
}

.elementor-image-carousel {
    margin-right: -30px; /* Shift the carousel to the left */
}

selector .swiper-slide-image {
    width: 100%;
    height: 360px;
    object-fit: cover;
}
```

This worked well , but having it as a core option would definitely improve flexibility!
