### ISSUE TITLE
Popup close button now awkwardly positioned

### ISSUE THREAD

**Issue by theDanielJLewis** [elementor/elementor#10921]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I apologize for not knowing exactly what version, only that it started with an update in the last few months. The popup close button has moved positions and now looks awkward.

I traced this to the `.dialog-close-button` CSS that is adding `margin-top: 15px`. But the div is already set to 20px from top and right.

Interestingly, it looks like this could be an accidental change because here's the full CSS:

```css
.dialog-close-button {
    cursor: pointer;
    position: absolute;
    margin-top: 15px;
    right: 15px;
    font-size: 15px;
    line-height: 1;
}
```

And then here's the override:

```css
.elementor-popup-modal .dialog-close-button {
    display: none;
    top: 20px;
    right: 20px;
    opacity: 1;
    z-index: 9999;
    pointer-events: all;
}
```

So note that the first block of text has `margin-top` and `right`, while the second block has `top` and `right`. It looks like `top` was accidentally changed to `margin-top`, especially since this wouldn't be a problem if it was `top`.
  
## Steps to reproduce

1. Create a new popup.
2. Look at a template and notice that the close button is supposed to be an equal distance from the top and right. ![Template preview](https://user-images.githubusercontent.com/154936/77234511-78384f00-6b85-11ea-8615-d2a319e060bc.png)
3. Use that template to create a popup.
4. Now see that close button is 15px too low and no longer evenly spaced from the top and right. ![Template in Elementor](https://user-images.githubusercontent.com/154936/77234514-7bcbd600-6b85-11ea-91a8-c3e1a7e0ad61.png)

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.
