### ISSUE TITLE
Controls_Manager::add_tab() how to add css icon?

### ISSUE THREAD

**Issue by EnterVPL** [elementor/elementor#12969]
I added
```css
.elementor-panel .elementor-tab-control-new-tab a:before {
	font-family: FontAwesome;
	content: '\f430';
}
```
to my css plugin but it's not working.

How to implement CSS for custom tabs? 

I tried this
``` php
add_action('wp_head', function() {
            echo '<style>.elementor-panel .elementor-tab-control-new-tab a:before {content: "\f430";}</style>';
    }, 100);
```
