### ISSUE TITLE
Remove "Edit Header" and "Edit Footer" options in Elementor editor for the role "Access to edit content only"

### ISSUE THREAD

**Issue by portrayaloflife** [elementor/elementor#13396]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Users with "access to edit content only" roles for pages etc and not elementor templates obv are seeing the "edit header" and "edit footer" options on hover when in the elementor editor which confuses them. They should have the option to access or see a button to access.

## Steps to reproduce

Login as a user with the role manger "access to edit content only" applied. Edit any page in elementor and hover over the header or footer. Option to edit them pops up and infinite load circle when clicked. 

Users at this level shouldn't be given that option to edit elementor theme builder templates. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by DorShahar** [comment]
Merged issue

I merged this issue with  #1314, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.
Thanks for your feedback!

**Comment by portrayaloflife** [comment]
Thanks!

**Comment by Suluuboi** [comment]
I found a way by just adding custom css to hide the buttons entirely.
```
.elementor .elementor-document-handle{
    display: none;
    visibility: hidden;
}
```

Or better yet if you would like to remove the edit buttons for all users but the admin you can install the plugin "Code Snippets" and add the code below.

```
add_action( 'wp_enqueue_scripts', 'wholesale_customer_logo' );
function wholesale_customer_logo(){
    if( in_array( 'wholesale_customer', (array) wp_get_current_user()->roles ) ){
        echo '<style>
            img.fusion-standard-logo {
                background: url(http://example.com/logo-for-wholesale-customers.png) no-repeat;
            }
        </style>';
    }
}
```

**Comment by flooweb214** [comment]
Thank you for that @Suluuboi,

To solve this problem, I was inspired by your solution.

I have chosen to add user role in body classe to have a reusable class in body for other things :
```php
/* Here $classes is an array */
add_filter('body_class', function($classes) {
	$user = wp_get_current_user();
    return array_merge($classes, $user->roles);
});

/* Here $classes is a string */
add_filter('admin_body_class', function($classes) {
	$user = wp_get_current_user();
    return $classes .' '. implode(' ', $user->roles);
});
```

After in the global Elementor css
```css
/* Prevent non admin to edit header and footer */
body:not(.administrator) .elementor .elementor-document-handle,
body:not(.administrator) #wp-admin-bar-elementor_edit_doc_5048,
body:not(.administrator) #wp-admin-bar-elementor_edit_doc_5050,
body:not(.administrator) #wp-admin-bar-elementor_edit_doc_7719,
body:not(.administrator) #wp-admin-bar-elementor_edit_doc_90687 {
    display: none;
    visibility: hidden;
}
```

Where #wp-admin-bar-elementor_edit_doc_XXXX are links I want to hide from not admin users.
![image](https://user-images.githubusercontent.com/1122699/217016792-76055a37-af3a-4d18-94e9-c2dc7d7683e9.png)
![image](https://user-images.githubusercontent.com/1122699/217016990-8bf0b0d8-07ae-47de-8343-8ac73a437aab.png)

With that it will harder for contributors to edit critical models.

I hope Elementor will improve soon the rights at least to prevent editing Header and Footer 🤞
