### ISSUE TITLE
HTML entities inside the new improved inlined CSS 

### ISSUE THREAD

**Issue by simkoG** [elementor/elementor#16140]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When I turn on the new "Improved CSS Loading" feature the `>` characters whitin the generated inline CSS are replaced with `&gt;` therefore the generated CSS is invalid. 

For example: 
```css
.elementor-widget-heading .elementor-heading-title[class*=elementor-size-]&gt;a{color:inherit;font-size:inherit;line-height:inherit}
                                                                          ⬆
```

## Steps to reproduce

1. Install clean Wordpress with Elementor (and Elementor Pro).
2. Activate Elementor (and Elementor Pro).
3. Go to Elementor > Settings > Experiments.
4. Set "Improved CSS Loading" to "Active".
5. Create a new Elementor page.
6. Add a "Header" element with some text and a `<a href="#">Sample</a>` tag inside of it.
7. Check the generated code and look for the sample mentioned above. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

[https://pastebin.com/XKb4a6ut](https://pastebin.com/XKb4a6ut)
