### ISSUE TITLE
Widget's "Custom CSS" styles not reflected properly on the frontend for some templates  

### ISSUE THREAD

**Issue by amyriounis** [elementor/elementor#17034]
We are dealing with a weird issue where custom styles added to a widget/element using the "Custom CSS" field end up being wrapped in a media query for no apparent reason. This happens **only** for the frontend, as in the editor it works ok.

Also, it happens **only** with certain templates, like the single-product template for example, but works ok in others.
<hr/>

Example:

Suppose we added this code in a widget in the editor:
```css
selector .random-class {
	color: red;
}
```

In the frontend, it becomes:
```css
@media (max-width: 767px) {
	.elementor-15879 .elementor-element.elementor-element-5b25fd62 .random-class {
		color: red;
	}
}
```
<hr/>

Video showcasing the issue: 
https://www.awesomescreenshot.com/video/6153462?key=3a09366dfc6bcef8651de2b0ba9f33e3

<hr/>
Clean WP installation with only Elementor/Elementor Pro & WooCommerce plugins active and Hello Elementor theme active.

WordPress v5.8.2
Elementor v3.4.8
Elementor Pro v3.5.1
