### ISSUE TITLE
❌ 🧩 🐞 Bug Report: Too broad CSS declarations for the `.swiper-wrapper` breaks other instances of the Swiper library

### ISSUE THREAD

**Issue by PulakAhmed** [elementor/elementor#23124]
### Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

### Description

Hi,

In the recent versions of the Elementor Pro, you added the following CSS code.

```css
.swiper-container:not(.swiper-container-initialized) .swiper-wrapper, .swiper:not(.swiper-initialized) .swiper-wrapper {
     gap: var(--e-n-carousel-swiper-slides-gap); 
     overflow: hidden; 
}
```

The **`overflow: hidden;`** property conflicts with the other carousel built on Swiper JS. Please include some identifiers before the CSS so it will not affect other plugins or carousels.

Look forward to your response.

Thank you.

### Steps to reproduce

If Elementor Pro is active, some sliders created with Swiper become blank due to the overflow hidden property. It's better to use a class that will help you to apply the code only on the Elementors swiper wrapper. Not on every swiper wrapper.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [ ] I can reproduce this bug consistently following the steps above.

### System Info

This information is not necessary on this topic
