### ISSUE TITLE
⛔ 🐞 Bug Report: Pseudo`::before` does not work correctly on Flexbox Container

### ISSUE THREAD

**Issue by hippopotam** [elementor/elementor#23664]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Using the code:

adding the border to div::after should show border on the right side of the box only -- this works as expected
adding the border to div::before should show border on the left side of the box only -- this does not work: instead, it adds border to all 4 sides

### Steps to reproduce

Add the custom code to flex box container:

```css
selector::before {
content:"";
border: 5px solid blue;
}
selector::after {
content:"";
border: 5px solid red;
}
```

First one creates borders on all 4 sides -- incorrect
Second one creates border on right side only -- correct

[Elementor flexbox bug with before pseudo-element.pdf](https://github.com/elementor/elementor/files/12514484/Elementor.flexbox.bug.with.before.pseudo-element.pdf)

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.57 (Unix) OpenSSL/3.1.2 PHP/8.2.10
	MySQL version: MySQL Community Server - GPL v8.0.31
	PHP Version: 8.2.10
	PHP Memory Limit: 512M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.3.1
	Site URL: xxxxxx
	Home URL: xxxxxx
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: xxxxxx
	Admin Email: xxxxxx
	Debug Mode: Inactive

== Theme ==
	Name: xxxxxx
	Version: 2023.0.1
	Author: xxxxxx
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.8.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15

== Active Plugins ==
	Elementor
		Version: 3.15.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.15.1
		Author: Elementor.com

	Pods - Custom Content Types and Fields
		Version: 2.9.19
		Author: Pods Framework Team

	Search & Filter
		Version: 1.2.16
		Author: Code Amp

	Unbloater
		Version: 1.6.1
		Author: Christoph Rado


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Global Style Guide: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Active
	Taxonomy Filter: Inactive by default


== Log ==
	
PHP: showing 7 of 7PHP: 2023-08-28 08:03:28 [notice X 1][xxxxxx/wp-content/plugins/elementor/core/upgrade/manager.php::62] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-28 08:08:16 [notice X 2639][xxxxxx/wp-content/plugins/elementor-pro/modules/loop-builder/module.php::204] strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-28 10:15:46 [warning X 5][xxxxxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key "data" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-28 20:32:15 [error X 7][xxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::295] Uncaught Error: Call to a member function update_meta() on null in xxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:295
Stack trace:
#0 xxxxxx/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(168): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(29, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 xxxxxx/wp-content/plugins/elementor/core/common/modules/ajax/module.php(175): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 xxxxxx/wp-includes/class-wp-hook.php(310): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 xxxxxx/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#5 xxxxxx/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 xxxxxx/wp-admin/admin-ajax.php(188): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-29 08:38:31 [notice X 1][xxxxxx/wp-content/plugins/elementor-pro/modules/screenshots/module.php::32] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-08-31 15:03:46 [notice X 1][xxxxxx/wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-09-02 11:32:50 [warning X 1][xxxxxx/wp-content/plugins/elementor-pro/modules/dynamic-tags/tags/site-logo.php::32] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2023-08-29 04:11:07 [error X 1][xxxxxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:54033] undefined is not an object (evaluating 'V.activate') 
JS: 2023-08-31 14:50:42 [error X 13][xxxxxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:917234] Can't find variable: elementorFrontend 
JS: 2023-08-31 15:08:04 [error X 12][xxxxxx/wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.3.1:2:28729] undefined is not an object (evaluating 'l[0].value') 
JS: 2023-09-01 05:13:19 [error X 124][xxxxxx/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.15.3:3:635419] undefined is not an object (evaluating 'B.model') 

Log: showing 5 of 52023-08-29 11:52:23 [info] elementor-pro::elementor_pro_updater Started 
2023-08-29 11:52:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-08-29 11:52:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-08-29 11:52:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.15.1',
)]
2023-08-29 11:52:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.2',
  'to' => '3.15.1',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

**Comment by nicholaszein** [comment]
Hello @hippopotam,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an Elementor Bug. This is the expected behavior. Here's why:
For performance reasons, Elementor applies by default some custom styles to the pseudo`::before` element of Containers when some features are used. These features are either **Background Overlays, Background Videos, Background Slideshows, or Motion Effects**. These are required to make these features work correctly, and are added as global styles for both backward compatibility as well as to reduce CSS sizes, since these are declared only once.

The custom CSS you are using is missing some important properties to ensure the elements you are using have the desired styles.

These are the CSS styles for the `::before` pseudo class of the container:

```css
.e-con::before {
    transition: 
        background var(--overlay-transition, 0.3s), 
        border-radius var(--border-transition, 0.3s), 
        opacity var(--overlay-transition, 0.3s);
}

.e-con::before, 
:is(.e-con, .e-con > .e-con-inner) > .elementor-background-video-container::before, 
.e-con > .elementor-motion-effects-container > .elementor-motion-effects-layer::before, 
.e-con > .elementor-background-slideshow::before {
    content: var(--background-overlay);
    display: block;
    position: absolute;
    mix-blend-mode: var(--overlay-mix-blend-mode);
    opacity: var(--overlay-opacity);
    transition: var(--overlay-transition, 0.3s);
    border-radius: var(--border-radius);
    border-style: var(--border-style);
    border-color: var(--border-color);
    border-block-start-width: var(--border-block-start-width);
    border-inline-end-width: var(--border-inline-end-width);
    border-block-end-width: var(--border-block-end-width);
    border-inline-start-width: var(--border-inline-start-width);
    top: calc(0px - var(--border-block-start-width));
    left: calc(0px - var(--border-inline-start-width));
    width: max(100% + var(--border-inline-end-width) + var(--border-inline-start-width), 100%);
    height: max(100% + var(--border-block-start-width) + var(--border-block-end-width), 100%);
}

.elementor *, 
.elementor *:before, 
.elementor *:after {
    box-sizing: border-box;
}

*, 
*::before, 
*::after {
    box-sizing: border-box;
}

```


### ✅ What you can do to solve your issue:
- Be more specific about the styles you want to apply to your pseudo classes:
   1. Set the **Position** property to **`Relative`**.
   2. **`Unset`** the **Top** and **Left** properties.
   3. Change the **Width** property.
   4. Change the **Height** property.
- Use another method to apply your custom styles, especially since you won't be able to use the aforementioned features if you try to use pseudo elements.

We have no plans to change the current styles or behaviors.

### 👍 For now, that's all we can help with. 

Kind regards
