### ISSUE TITLE
The Color control overwrites non-{{VALUE}} css-property values in the selectors option.

### ISSUE THREAD

**Issue by pryley** [elementor/elementor#29002]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The Color control "selectors" option overwrites non-{{VALUE}} css-property values.

For example, here is a color control:

```php
$this->add_control('rating_color', [
    'global' => [
        'default' => \Elementor\Core\Kits\Documents\Tabs\Global_Colors::COLOR_TEXT,
    ],
    'label' => esc_html__('Color', 'site-reviews'),
    'selectors' => [
        '{{WRAPPER}} .glsr-star-full' => 'background: {{VALUE}}; mask-image: var(--glsr-star-full); mask-size: 100%;',
    ],
    'type' => \Elementor\Controls_Manager::COLOR,
]);
```

CSS output for the control when a color is selected should be this:
 
```css
.elementor-38564 .elementor-element.elementor-element-7ad2e33 .glsr-star-full {
    background: var( --e-global-color-accent );
    mask-image: var(--glsr-star-full);
    mask-size: 100%;
}
```

Instead, the CSS output looks like this:

```css
.elementor-38564 .elementor-element.elementor-element-7ad2e33 .glsr-star-full {
    background: var( --e-global-color-accent );
    mask-image: var( --e-global-color-accent );
    mask-size: var( --e-global-color-accent );
}
```

### Steps to reproduce

Add the following control to a widget (replace the css-selector as needed):

```php
$this->add_control('rating_color', [
    'global' => [
        'default' => \Elementor\Core\Kits\Documents\Tabs\Global_Colors::COLOR_TEXT,
    ],
    'label' => esc_html__('Color', 'site-reviews'),
    'selectors' => [
        '{{WRAPPER}} .glsr-star-full' => 'background: {{VALUE}}; mask-image: var(--glsr-star-full); mask-size: 100%;',
    ],
    'type' => \Elementor\Controls_Manager::COLOR,
]);
```

The CSS output looks like this:

```css
.elementor-38564 .elementor-element.elementor-element-7ad2e33 .glsr-star-full {
    background: var( --e-global-color-accent );
    mask-image: var( --e-global-color-accent );
    mask-size: var( --e-global-color-accent );
}
```

Notice that the CSS is invalid because Elementor has replaced all css-property values with the color value instead of only replacing the {{VALUE}} placeholder.

### Expected behavior

CSS output for the control when a color is selected SHOULD look like this instead:
 
```css
.elementor-38564 .elementor-element.elementor-element-7ad2e33 .glsr-star-full {
    background: var( --e-global-color-accent );
    mask-image: var(--glsr-star-full);
    mask-size: 100%;
}
```

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Darwin
	Software: nginx/1.25.4
	MySQL version: Homebrew v8.4.2
	PHP Version: 8.3.12
	PHP Memory Limit: -1
	PHP Max Input Vars: 5000
	PHP Max Post Size: 24M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 64M
	Max Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: Europe/Dublin
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; rv:131.0) Gecko/20100101 Firefox/131.0

== Active Plugins ==
	Elementor
		Version: 3.24.7
		Author: Elementor.com

	Site Reviews
		Version: 7.2.0
		Author: Paul Ryley


== Must-Use Plugins ==


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active
	Flexbox Container: Active
	Grid Container: Active
	Upgrade Swiper Library: Active
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	Header & Footer: Inactive by default
	Elementor Home Screen: Active by default
	Build with AI: Active
	Landing Pages: Active
	Launchpad Checklist: Inactive by default
	Nested Elements: Active
	Editor Top Bar: Active
	Pages Panel: Inactive by default
	Element Caching: Active
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default


== Log ==


== Elementor - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.
