### ISSUE TITLE
⛔ Line-height applied to .elementor-button-text in the current Kit prevents other line-height settings to be inherited by the Button widget

### ISSUE THREAD

**Issue by faisalbinali12** [elementor/elementor#30544]
### Prerequisites

- [x] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

**Elementor auto-generates button line-height CSS, which I can't adjust from the Global settings or even for individual elements. Upon inspecting, I noticed that Elementor is generating the following CSS for the button line height:**  

```css
.elementor-kit-6 .elementor-button-text {
    line-height: 1em;
}
```  

This CSS selector directly targets the `span` tag with the `elementor-button-text` class, but Elementor applies the CSS to its grandparent element. This mismatch causes the issue.  

To resolve it, I wrote custom CSS (see attached pin 1) to override the generated CSS.  

![Image](https://github.com/user-attachments/assets/86f7a45d-661b-468e-8e3d-f69034779e00)

### this is what Elemetor Generate for individual Elements

![Image](https://github.com/user-attachments/assets/fbbbd0b9-50f2-4574-adfb-52ea1b47ad1d)

### Steps to reproduce

This bug happens occasionally, and I’m unsure why or how, but it does occur from time to time.

### Expected behavior

This CSS [attac pin 2] selector directly targets the `span` tag with the `elementor-button-text` class, but Elementor applies the CSS to its grandparent element. This mismatch causes the issue.  

To resolve it, I wrote custom CSS (see attached pin 2) to override the generated CSS.  

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.16
	PHP Version: 8.1.29
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 16384
	PHP Max Post Size: 1536M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.2
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/Detroit	Debug Mode: Inactive

== Theme ==
	Name: Woostify
	Version: 2.3.9
	Author: Woostify
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: 

== Active Plugins ==
	Classic Editor
		Version: 1.6.7
		Author: WordPress Contributors

	Elementor
		Version: 3.27.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.27.6
		Author: Elementor.com

	Flexible Elementor Panel
		Version: 2.5.1
		Author: WebMat


== Must-Use Plugins ==
	Nexcess Managed Apps
		Version: 1.54.0
		Author: Nexcess


== Elements Usage ==
	
	archive : 1
		container : 3
		heading : 1
		html : 1
		loop-grid : 1
	container : 1
		container : 2
		heading : 1
		text-editor : 1
	footer : 1
		container : 2
		icon-list : 1
		image : 1
		social-icons : 1
		text-editor : 1
	header : 2
		button : 2
		container : 6
		icon : 2
		image : 1
		nav-menu : 2
	popup : 1
		button : 1
		container : 1
		nav-menu : 1
	wp-post : 2
		button : 1
		container : 2
		text-editor : 3
	wp-page : 8
		button : 16
		container : 180
		form : 4
		heading : 66
		icon-box : 3
		icon-list : 2
		image : 34
		image-box : 3
		nested-accordion : 2
		text-editor : 42
		video : 21
	single-post : 1
		container : 6
		heading : 3
		image : 1
		share-buttons : 1
		theme-post-content : 1
	loop-item : 1
		container : 3
		heading : 3
		image : 1
		text-editor : 1


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Container: Active by default
	Upgrade Swiper Library: Active by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Load Google Fonts locally: Inactive by default
	Default to New Theme Builder: Active by default
	Elementor Home Screen: Active by default
	Landing Pages: Inactive by default
	Nested Elements: Active by default
	Editor Top Bar: Inactive
	Element Caching: Active by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Global Classes: Inactive by default
	Launchpad Checklist: Active by default
	Menu: Inactive by default


== Log ==
	
Log: showing 15 of 152025-03-07 12:17:15 [info] elementor-pro::elementor_pro_updater Started 
2025-03-07 12:17:15 [info] Elementor Pro/Upgrades - _on_each_version Start  
2025-03-07 12:17:15 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2025-03-07 12:17:15 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.26.2',
  'to' => '3.27.5',
)]
2025-03-07 12:17:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.26.2',
  'to' => '3.27.5',
)]
2025-03-11 15:52:49 [info] elementor-pro::elementor_pro_updater Started 
2025-03-11 15:52:49 [info] Elementor Pro/Upgrades - _on_each_version Start  
2025-03-11 15:52:49 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2025-03-11 15:52:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.27.5',
  'to' => '3.27.6',
)]
2025-03-11 15:52:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.27.5',
  'to' => '3.27.6',
)]
2025-03-14 16:54:22 [info] elementor::elementor_updater Started 
2025-03-14 16:54:22 [info] Elementor/Upgrades - _on_each_version Start  
2025-03-14 16:54:23 [info] Elementor/Upgrades - _on_each_version Finished 
2025-03-14 16:54:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.27.6',
  'to' => '3.27.7',
)]
2025-03-14 16:54:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.27.6',
  'to' => '3.27.7',
)]

JS: showing 5 of 5JS: 2025-03-09 00:37:05 [error X 3][../elementor/assets/js/editor.min.js?ver=3.27.6:3:802371] Cannot read properties of undefined (reading 'localized') 
JS: 2025-03-11 19:43:17 [error X 9][../wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.7.2:2:28760] Cannot read properties of undefined (reading 'subscribe') 
JS: 2025-03-11 19:45:53 [error X 2][../elementor/assets/js/ai-gutenberg.min.js?ver=3.27.6:3:382224] Cannot read properties of undefined (reading 'useSelect') 
JS: 2025-03-12 21:22:08 [error X 3][../wp-includes/js/jquery/jquery.min.js?ver=3.7.1:2:51327] Cannot read properties of undefined (reading 'appendChild') 
JS: 2025-03-14 19:12:53 [error X 1][../elementor/assets/js/editor.min.js?ver=3.27.6:3:591202] Cannot read properties of null (reading 'id') 

PHP: showing 3 of 3PHP: 2025-03-11 16:45:08 [warning X 13][../elementor/includes/embed.php::186] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2025-03-14 15:40:16 [warning X 3][../elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: ../elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2025-03-14 17:19:06 [warning X 4][../elementor/modules/history/revisions-manager.php::363] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Flexible Elementor Panel: Compatible

== Elementor Pro - Compatibility Tag ==
	
	Flexible Elementor Panel: Compatible

````

</details>

### Agreement

- [x] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hi @faisalbinali12!

Thank you for reaching out! 🙏 

While troubleshooting your issue we see a few things that don't match Elementor's default behavior. By default Elementor has 3 levels of inheritance for button line-height, that are overwritten depending on where the styles are applied.

### Level 1 (Base styles):
These styles are applied by default. If no other style is applied, these values will be inherited.
```css
/* ..path/to/elementor/assets/css/frontend.css */

.elementor-button {
    /* ... */
    line-height: 1;
    /* ... */
}
```

### Level 2 (Site Kit styles):
These are the styles set in the Elementor **`Editor`** > **`Site Settings`** > **`Theme Style`** > **`Buttons`** > **`Typography`** > **`Line Height`**, and will override the base styles.
```css
/* ..path/to/uploads/elementor/css/post-{{ID}}.css : where {{ID}} is the ID of the current Site Kit / Site Settings */

.elementor-kit-{{ID}} .elementor-button {
    /* ... */
    line-height: 1.5em; /* 1.5em is an example. If nothing is set, this property is not loaded. */
    /* ... */
}
```

### Level 3 (Document > Widget styles):
These are the styles set individually for each widget in a Document (Post, Page, Template). In this case in the Button **`Widget`** > **`Styles`** tab > **`Typography`** > **`Line Height`**, and will override the Site Kit styles if they exist, otherwise they will override the Base styles.
```css
/* ..path/to/uploads/elementor/css/post-{{ID}}.css : where {{ID}} is the ID of the Document where the widget resides. */

.elementor-{{ID}} .elementor-element.elementor-element-{{WIDGET_ID}} .elementor-button {
    /* ... */
    line-height: 2em; /* 2em is an example. If nothing is set, this property is not loaded. */
    /* ... */
}

You can see this in action in the video I recorded below:

https://github.com/user-attachments/assets/469c6669-1082-4341-b387-04503c09a87a

### Conclusion
Notice a common pattern between all 3 levels? None of them apply styles to `.elementor-button-text`, instead all the 3 declarations apply styles to **`.elementor-button.`** That's because if needed, you can apply your own styles to `.elementor-button-text`, since by default it should **inherit** the styles from **`.elementor-buttn`**. Which is what I think is happening in your case. Here's why:

From the first image you shared, I can see declaration below. This indicates that Custom CSS was applied to your Site Settings:
```css
.elementor-kit-6 .elementor-button-text {
    line-height: 1em;
}
```

If you go to the Elementor **`Editor`** > **`Site Settings`** > **`Settings`** > **`Custom CSS`** and write the declaration below, it will effectively override the other declarations, since you're applying the style directly to the `.elementor-button-text` class.
```css
/* ..path/to/uploads/elementor/css/post-{{ID}}.css : where {{ID}} is the ID of the current Site Kit / Site Settings */

selector .elementor-button-text {
    line-height: 1em;
}
```

You can see this in action in the second video I recorded below:

https://github.com/user-attachments/assets/965ae1f3-532e-45ba-b089-147749ca7a60

Based on this information, it seems you have **`Custom CSS`** in your Site Settings that is overriding the default behavior of Elementor. Review the styles you applied there, and make sure to remove the existing CSS.

If you don't see that declaration in your **`Site Settings`** > **`Custom CSS`**, you can try the following:

1. Go back to the **`Theme Style`** > **`Buttons`** section.
2. Under the **`Typography`** settings, click on the **Reset** button (represented by a reverse-circular arrow).
3. **Save Changes** in the Site Settings panel's footer, and **close the editor**.
4. Open the editor again, and go back to the **`Site Settings`** > **`Theme Style`** > **`Buttons`** section.
5. Under the **`Typography`** settings, apply your preferred global `line-height` and finally **Save Changes**. 

### 🛟 This is more of a personal support request, which we can't assist with here.

#### GitHub issues are reserved only for [confirmed Elementor 🐞 Bug Reports](https://elemn.to/gh-contributing-bug-reports). We are unable to provide personal support or assistance through GitHub, but we have dedicated channels for assistance.

> [!TIP]
>  Before submitting an issue, check the **[Help Center](https://elemn.to/gh-to-help-center)** or contact **[Elementor Support](https://elemn.to/support-ticket).**
> This saves time and aligns with our **[Contribution Guidelines](https://elemn.to/gh-contributing).**
> Make sure you also troubleshoot your issue and isolate the problem before submitting your Bug Report.

> [!NOTE]
> ### 🛟 Support Request issues may be closed without troubleshooting.
> To ensure smooth issue resolution, follow our **[🐞 Bug Report Guidelines](https://elemn.to/gh-contributing-bug-reports).**

I'm closing this issue as it is not a bug.

Thanks for understanding! 🙏

Kind regards
