### ISSUE TITLE
✔️ 🚀 Feature Request: Improve column gap behavior

### ISSUE THREAD

**Issue by ajlcomputers** [elementor/elementor#4097]
Currently all the column gap option does is add some padding to the columns. This doesn't work for a number of reasons.

1) If I add a background colour to all the columns then the spacing between them is also filled with the background colour meaning there's no gap at all.

2) The padding is on all sides of the column so any content now doesn't line up with full width content on the far left or the far right of the page.

3) If I add my own padding to the column then this overrides the column gap option.

As you can tell, all this renders the column gap option basically useless. I would suggest that it's altered to be an input box where you can specify the number of pixels that you want between the columns, it should not add any space on the left of the first column or the right of the last column and it should leave all columns the same width.

Also, it should add the same pixel gap between columns when they are stacked vertically in tablet or mobile view.

**Comment by asadkn** [comment]
This is a major issue for new users. For such a **basic feature** handled by column settings in all other builders, users of Elementor have to mess with padding and margins for each column - which come easily to a web developer (even though it's wasted time and effort) but not to a regular user. I am not sure how was this overlooked for so long.

Besides what @ajlcomputers already mentioned, there's another important issue:

- If you want two columns with any element inside, let's say text - and add a column gap, now there's extra space on left and right since there are no negative margins to bring it back to match everything else.

Here's what I would suggest to remain backward compatible:

- Rename existing setting to Column Inner Gap or just Column Padding. 

- Add a new setting for proper Column Gap. Since we aren't using proper CSS grids yet, this would have to be done using margins on columns / negative margins on the container.

**Comment by beauwalsh** [comment]
Agreed! The Column Gap setting is pretty useless because of the outside edges, which throws off the overall design.

**Comment by black-eye** [comment]
+1

**Comment by JimmyHowe** [comment]
+1

**Comment by binhnguyen214** [comment]
+1

**Comment by GriswaId** [comment]
I've made a few websites with Elementor now, and I find the best way around this problem is to simply add another column or inner section inside the columns you are wanting to seperate. 

<img width="212" alt="Screen Shot 2019-05-03 at 4 12 43 pm" src="https://user-images.githubusercontent.com/50227877/57122052-84c18680-6dbe-11e9-9727-b666d51ff7f0.png">

This works best when using REM or EM margins and padding, as it retains responsiveness and scale when viewed on different devices.

**Comment by pensierinmusica** [comment]
+1

**Comment by SquareInternet** [comment]
@ajlcomputers @pensierinmusica @GriswaId @black-eye @JimmyHowe @binhnguyen214 @beauwalsh would you pay for this as an add on if it were say $5-10?

We also are in want of a posts filter system and are thinking of developing one. We recently made this to deal with no infinite scroll - https://squareinternet.co/elementor-infinite-scroll/

**Comment by SquareInternet** [comment]
@ajlcomputers @pensierinmusica @GriswaId @black-eye @JimmyHowe @binhnguyen214 @beauwalsh 

Hey everyone. Here's a solution for this - https://squareinternet.co/fixing-no-elementor-column-gap/

It's not a 'built in fix' but it takes 20 sec to do this, hopefully it helps you.

**Comment by ZahidulKabir-dotCom** [comment]
Set left and right margin for each column
![screenshot](https://user-images.githubusercontent.com/53332475/61935680-d4be7c80-afac-11e9-9a38-3c89d6af5a3e.jpg)

**Comment by ajlcomputers** [comment]
> Set left and right margin for each column
> ![screenshot](https://user-images.githubusercontent.com/53332475/61935680-d4be7c80-afac-11e9-9a38-3c89d6af5a3e.jpg)

This is currently the best way to do it but it's not really ideal. If I want 3 columns with 20px between each column and all 3 columns to be equal then it's not possible to achieve it.

All you could do is add 10 right on the first column 10 left and 10 right on the middle one and then 10 left on the last one. The problem there is that the central column is now 10px smaller than the outside ones as it has twice the margin applied to it. 

You also then have to change all the margins for the tablet and mobile views. This is a pain when a simple column gap option where you put in the number of pixels you want between the columns and that applies the same gap between each column and then vertically when they stack. Much simpler and quicker for users.

**Comment by bentalgad** [comment]
BBBBBAAAAASSSSSSIIIIICCCCC

**Comment by davidamarek** [comment]
+1

**Comment by bramdebouvere** [comment]
+1

**Comment by tbba** [comment]
+1

**Comment by JoshBreda** [comment]
If I have the kind of problem. If I use Elementor products to make a product list, I set the column gap on 0, but the gap remains huge, resulting in very small and cropped images and almost no space for text. This is awful.

**Comment by avermat** [comment]
Please update this.

1) I think it would make more sense to have two separate options/fields, "column padding" and "column gap" or you could use "column gap (padding)" and "column gap (margin)".

2) It would be helpful to be able to manually enter a number instead of choosing from the drop-down where the number is a mystery and it maxes out at 30px. Also, I'm forced to use the same gap on desktop, tablet, and mobile?

3) Column gaps (margins) should not be applied to the left margin of the first column and right margin of the last column as mentioned earlier.

**Comment by brentbarkley** [comment]
+1  "column gap" suggests it uses CSS grid or behaves like it. It obviously doesn't. Rarely or never would anyone set up a columnar layout on a page and not want the outsides to line up with the rest of the wraps on the page. (!!!)

**Comment by plethoradesign** [comment]
There really ought to be a simple option to set left/right margins of 0, and have columns space evenly with gaps in between.  Elementor uses Flexbox CSS, but not in an ideal way, because it applies padding/margins to child elements of the columns - not to the columns themselves. I get why ... they want people to be able to specify the gap size. But I think it would be better if the column width were set based on some simple math, e.g.:

User selects a 50%-width column but wants column gaps of 40px AND no gap at the left/right of the columns. Then Elementor should render this as `width=calc(50% - 20px)` if it's a 2-column layout where each column is 50%. For 3-columns layouts it would be more difficult.

It would be great if Elementor could support such scenarios using easy presets, at least for 2 and 3-column layouts. 

For now I am stuck manually setting padding on my columns, three times per column (for desktop, tablet, and mobile). It shouldn't be this painful for site editors/owners to do.

**Comment by ValerieEskens** [comment]
+1!!!

**Comment by mrwhizzy** [comment]
Wow, I wasted quite some time until I found out that this is actually an open issue on Elementor. What's even more unbelievable, is the fact that this is open since April 2018, which is more than 2.5 years ago.

**Comment by hybridvision** [comment]
I agree that this is far from ideal but I'm not sure that we'll see an official fix from Elementor any time soon because of all the possible issues it might cause on the millions of websites already deployed.

Fortunately, it's possible to fix this globally for an individual site by adding some extra CSS to your theme that will override the default Elementor CSS while still making it possible to add custom margins / padding to a column when needed.

Before I get to my solution, I should point out that this is further complicated by the fact that Elementor 3.0+ has changed the underlying HTML structure for sections and columns. Since it's potentially breaking change, it will be disabled for older sites that have upgraded from Elementor 2.x to 3.x. New sites should have it by default. You can read more about it [here](https://developers.elementor.com/dom-improvements-ahead-html-wrappers-removal-from-v3-0/) and [here](https://elementor.com/help/what-is-the-optimized-dom/).

With that out of the way, I'm sharing my solution that works with the **new HTML structure** mentioned above. If for some reason, you still need to use the older structure, it shouldn't be too hard to adapt it. My solution works _regardless_ of the number of columns you have.

Here's my CSS with some explanatory comments:

```css
/* 
Firstly, remove the default padding Elementor adds to columns containing content.
We don't want this because it causes slight mis-alignments and when you use a background colour, 
it bleeds out around the elements. Content should sit flush with the column edge by default.
*/
.elementor-container > .elementor-column > .elementor-element-populated {
  padding: 0;
}

/* 
Next, the various column gap settings.
Elementor changes the class on the container element depending on the column gap setting.

These are the possible "gap" classes:

.elementor-column-gap-default
.elementor-column-gap-no (no gap)
.elementor-column-gap-narrow
.elementor-column-gap-extended
.elementor-column-gap-wide
.elementor-column-gap-wider

You should override these as you see fit. 
I won't include them all but I'll give an example below:
*/

/*== "Extended" gap (60px in this example) ==*/
/* Apply a left-hand margin of 30px to all columns except the first */
.elementor-column-gap-extended > .elementor-column:not(:first-of-type) {
  margin-left: 30px; /* Half of total desired gap */
}

/* Apply a right-hand margin of 30px to all columns except the last */
.elementor-column-gap-extended > .elementor-column:not(:last-of-type) {
  margin-right: 30px; /* Half of total desired gap */
}

/*... Repeat the above pattern for each of the column gap classes ...*/

/* 
Since we're adding margins to columns, we need to ensure that flexbox wrapping is disabled 
until we actually want it to take effect. Elementor activates wrapping below the "Tablet" breakpoint 
that is defined in the Site Settings panel. In my case, I want to control this separately (see next section)
*/
.elementor-section .elementor-container {
    flex-wrap: nowrap;
}

/* 
When columns wrap, we need to remove our "gap" margins since there will only be 1 column now.
Adjust this breakpoint to suit your design:
*/
@media only screen and (max-width: 767px) {
  .elementor-container > .elementor-column {
    margin-left: 0 !important;
    margin-right: 0 !important;
  }

  /* Full width, single columns */
  .elementor-section .elementor-column {
    width: 100% !important;
  }
}
```

It took me a while to figure this out and I'm finally getting around to sharing it. Hopefully it helps save someone else a bit of time. Good luck!
