### ISSUE TITLE
CSS Styling Conflict on multiple instances of same widget on same page.

### ISSUE THREAD

**Issue by asoni7039** [elementor/elementor#7095]
Hello there,
I am learning to develop Elementor Addons. I have two questions.
First : What does prefix_class argument do in add_control function ?
Second : When i use a widget more than once in a same page/post sometimes when i apply some css via elementor editor to its single instance it automatically gets applied to the other instances used in another places of the same page. How can i make this happen when i make changes only at its first instance, it only applies to only first instance not everywhere( widgets where used more than once).
Thanks for your help.

**Comment by webangon** [comment]
Where do you get prefix_class in add_control function? Please share your code to help other understand what you are trying to do .

**Comment by shilo-ey** [comment]
Hi @asoni7039 

Simply use `selector` before your CSS rule.

Use "selector" to target wrapper element. Examples:
```CSS
selector {color: red;} // For main element
selector .child-element {margin: 10px;} // For child element
.my-class {text-align: center;} // Or use any custom selector
```
