### ISSUE TITLE
Add Button Icon on Elementor Image Slider

### ISSUE THREAD

**Issue by RoldanAncajas** [elementor/elementor#7290]
Hi Elementor,

How do I put an ICON in the button inside the picture slider.

Kindly check attached file.

![screen shot 2019-03-03 at 4 48 56 pm](https://user-images.githubusercontent.com/48211630/53736726-860d2a80-3ec5-11e9-9480-0cfd5829bd0b.png)

Best Regards,

Roldan Ancajas

**Comment by shilo-ey** [comment]
Hi @RoldanAncajas 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now, the only way you can do so is by applying Custom CSS. e.g:
```CSS
selector .elementor-button.elementor-slide-button::before {
    content: "\f087";
    font-family: FontAwesome;
    margin-right: 20px;
}
```

Place it inside your Slider Advanced tab > Custom CSS

Thanks
