### ISSUE TITLE
Accordion widget: Icon and Text cannot alignment in same line

### ISSUE THREAD

**Issue by ThornSTEPS** [elementor/elementor#7516]
Dear Support,

In Accordion widget, Icon and Text cannot alignment in same line

It's happened when we set line-height to Text but Icon still have fix line-height.

Could you help fix it?

Please see attached image for more detail.

URL: https://stepstraining.co/digital-branding

![accordion](https://user-images.githubusercontent.com/48666631/54507472-1fcbe180-4974-11e9-916b-df80c634c181.png)

Best regards,
Thorn

**Comment by shilo-ey** [comment]
Hi @ThornSTEPS 
The line-height property seems to come from your headers custom CSS (but it's minified so we can't know for sure):
```CSS
@media (max-width: 767px)
.elementor-39066 .elementor-element.elementor-element-138d3d3c .elementor-accordion .elementor-tab-title {
    line-height: 1.9em;
}
```


Remove it and it should be fine.

Thanks

**Comment by ThornSTEPS** [comment]
Hi @shilo-ey 

We don't want to remove line-height from text setting. Because it make users easy to read.

Do you have any solution to fix it?

Thanks
Thorn

**Comment by shilo-ey** [comment]
[**@ThornSTEPS**](https://github.com/ThornSTEPS) commented on [Mar 19, 2019, 10:49 AM GMT+2](https://github.com/elementor/elementor/issues/7516#issuecomment-474250417 "2019-03-19T08:49:45Z - Replied by Github Reply Comments"):
> Hi @shilo-ey 
> 
> We don't want to remove line-height from text setting. Because it make users easy to read.
> 
> Do you have any solution to fix it?
> 
> Thanks
> Thorn

That's what causing the lines not being aligned.

You can set line height to 1.9em:

```CSS
.elementor-accordion .elementor-tab-title .elementor-accordion-icon .elementor-accordion-icon-closed {
    line-height: 1.9em;
}
```
