### ISSUE TITLE
[Feature Request] Add Ability to change underline color in typography settings

### ISSUE THREAD

**Issue by jazir5** [elementor/elementor#7553]
I cannot find a setting to change the color of the underline from the default when underlining text in typography settings. This is a big issue for color consistency across the sites i am developing.

**Comment by shilo-ey** [comment]
Hi @jazir5 

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

For now you can use custom CSS for this specific behavior:
```CSS
.elementor-widget-text-editor, .elementor-heading-title {
	text-decoration-color: red;
}
```

Thanks for the feedback.
