### ISSUE TITLE
Navbar animation disable

### ISSUE THREAD

**Issue by Haxsan** [elementor/elementor#7591]
İ want mobile navbar dropdown menu animation none or disable help me please
This is video https://youtu.be/5iWTlMWRlWQ
İ dont want animation

**Comment by shilo-ey** [comment]
Hi @Haxsan 

Please try adding this CSS:

```CSS
.elementor-nav-menu--toggle .elementor-menu-toggle.elementor-active + .elementor-nav-menu__container, .elementor-nav-menu--toggle .elementor-menu-toggle:not(.elementor-active) + .elementor-nav-menu__container {
    transform: none;
}
```

Thanks.
