### ISSUE TITLE
Elementor Posts Widget Title Length

### ISSUE THREAD

**Issue by wacaszafar** [elementor/elementor#7714]
The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Elementor Pro Posts widget does not have the option to set number of words or characters to show in title heading of the post.

**What problem is your feature request going to solve? Please describe.**
Lack of setting length on the title heading widget causes uneveness and distorts balance if a number of posts are shown because post title heading will be different for different posts.

**Describe the solution you'd like**
I would like the option to set the length of title heading by number of characters or words so if for example 2 posts are showing with varying lengths in the column it will show as as balanced since all posts will be set at a set number of words. 
Also possibly of adding a suffix like three dots at the end of the post incase the title lenght increases by the set number of words / characters.

**Comment by shilo-ey** [comment]
Hi @wacaszafar 
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Please try using this CSS rule:

```CSS
.elementor-widget-posts .elementor-post__title{
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    max-width: 80px; /* set your desired width */
}
```

Thanks for the feedback.
