### ISSUE TITLE
Menu Cart widget - adding own cart icons to the list. With Fontello? 

### ISSUE THREAD

**Issue by kcynia85** [elementor/elementor#7976]
Hey,

I wanted to replace my own cart icon to the Menu Cart widget. Unfortunately, it is impossible.
There are a couple of default icons which don't fit for my layout. I know that third-party widget named "Custom Icons for Elementor" where I am able to icons to Elementor library. 

Actually "Custom Icons for Elementor" feature is a cool thing but as I was saying I would like to change a cart icon in the Menu Cart widget and a mentioned third-party doesn't have access.

Is there any way to add own icon to the list directly to the core assets and then add some path to the added icon to code? 

Please for your help on how to resolve icons issue. 

PS The same thing connected to The Search Form widget.
<img width="1440" alt="Screen Shot 2019-04-27 at 3 05 00 PM" src="https://user-images.githubusercontent.com/40715208/56850105-fe103380-68fd-11e9-8c8a-92473374fbf4.png">

**Comment by shilo-ey** [comment]
Hi @kcynia85 

Thanks for your feedback,

First, this is not an issue, but a feature request.

Currently, this feature is not supported, but you can use custom CSS to achieve this behavior.

Thanks.

**Comment by ManageFlaiks** [comment]
Hi Shilo, what's the custom CSS for doing so? I'm having issues figuring that one out, cheers.

**Comment by shilo-ey** [comment]
For example:

```CSS
.elementor-widget-woocommerce-menu-cart.toggle-icon--cart-medium .elementor-menu-cart__toggle .elementor-button-icon i:before {
    content: '';
    font-family: FontAwesome;
}
```

This feature will be added in the upcoming versions. stay tuned.
