### ISSUE TITLE
How do I place the agreement field after the submit button ?

### ISSUE THREAD

**Issue by GOHA81177** [elementor/elementor#8001]
Hi 
Asked in technical support question
"How do I place the agreement field after the submit button ?"

I said that's what:

Kai replied 
Hi,Thank you for contacting us.Unfortunately the form widget has no controls to switch the order of the acceptance field and the submit button.This will require custom CSS which is beyond the scope of this support.In any case, I tagged this ticket as a feature request so this will be included in the upcoming future updates.In the meantime, please also post this to our Github page so our developers can help you with the required custom CSS to accomplish this.To post on our Github Repository, you can follow this guide: https://github.com/pojome/elementor/blob/master/.github/CONTRIBUTING.mdPlease let them know were referred by the support team so they would know that you've already contacted us first.Kind regards,

How to solve the problem ?

**Comment by shilo-ey** [comment]
Hi @GOHA81177 

Thanks for your feedback.

This feature is not available in Elementor, and probably won't be implemented soon.
With that said, you can add your own custom CSS to the `<form>` and each of the fields to achieve this.


1. Set custom `ID` to each field (e.g "full_name", "email", "acceptance")
2. Add the following custom CSS:
```CSS
form.elementor-form {
    flex-direction: column;
    display: flex;
}
.elementor-field-group-full_name {
    order: 1;
}
.elementor-field-group-email {
    order: 2;
}
.elementor-field-group.elementor-column.elementor-field-type-submit {
    order: 3;
}
.elementor-field-group-accept {
    order: 4;
}
```

That way you can reorder your fields.

Thanks
