### ISSUE TITLE
Default column gap

### ISSUE THREAD

**Issue by boutzamat** [elementor/elementor#8038]
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

> **What problem is your feature request going to solve? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

When i have to set the gap size per section. My preffered default gap size is "wide (15px)".

> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
An option in the settings page/editor that allows you to select a default gap size.

> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
The manual way. Tried custom CSS solutions but either it's overriding any custom setting (My CSS class is too directly targeted) or it is being overrided by Elementors default CSS, due to Elementors CSS priorities.

> **Additional context**
> Add any other context or screenshots about the feature request here.
Please? :D

**Comment by shilo-ey** [comment]
Hi @boutzamat 

Try adding this to your CSS file:
```CSS
.elementor-column-gap-default > .elementor-row > .elementor-column > .elementor-element-populated {
    padding: 15px; /* set your desired padding */
}
```

Thanks
