### ISSUE TITLE
[Elementor Hello Theme / WP 2019 Theme] align styles clash with figure styles

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#8084]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The following line of code clashes with WP's default align styles, as referenced in Elementor Hello theme:

Elementor
assets/css/frontend.css:120:
```css
  .elementor .elementor-widget:not(.elementor-widget-text-editor) figure {
    margin: 0; }
```

Elementor Hello Theme
style.css:Line 738:
```css
.alignright {
  float: right;
  margin-right: 1rem; }

.alignleft {
  float: left;
  margin-left: 1rem; }

.aligncenter {
  clear: both;
  display: block;
  margin-left: auto;
  margin-right: auto; }
```

The result is that default margin styles are overridden, which removes spacing on all regular WP post images:

![image](https://user-images.githubusercontent.com/1435638/57505316-0bceab80-7337-11e9-9ff7-bb8264f1c9f0.png)

![image](https://user-images.githubusercontent.com/1435638/57505096-2ce2cc80-7336-11e9-826d-69b960ebca31.png)

Correct appearance:
![image](https://user-images.githubusercontent.com/1435638/57505303-f9547200-7336-11e9-824a-10a4932708d0.png)

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.
