### ISSUE TITLE
Soundcloud widget Height-Resize - Would be great to have this feature to remove a few pixels height

### ISSUE THREAD

**Issue by d27admino** [elementor/elementor#8098]
Hi,

REQUEST: it would be great to be able to resize the height of the soundcloud module. 

REASON : With a short playlist, there is a lot of uncessary space. 

It is the same with Spotify playlists, there is a lot of lost space even though it is smaller.

Thanks

**Comment by shilo-ey** [comment]
Hi @d27admino 

Use custom CSS to achieve this:

```CSS
.elementor-soundcloud-wrapper iframe {
    height: 200px; /* change to the height you wish */
}
```

Thanks
