### ISSUE TITLE
[Suggestion] Improve icon contrast in edit panel

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#8530]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The new icon library system in 2.6 is awesome, however the icon viewer in the edit panel is hard to read in some occasions (the grey colour doesn't contrast well enough against the checkerboard background). 

![image](https://user-images.githubusercontent.com/1435638/61014239-9f6b3980-a3c5-11e9-86a0-e66b8f30d730.png)

**Describe the solution you'd like**
A quick adjustment to the CSS of the edit panel, to make the icons higher contrast. This will improve accessibility.

![image](https://user-images.githubusercontent.com/1435638/61014265-c295e900-a3c5-11e9-9874-befaeaa74f04.png)

```css
.elementor-control-type-icons .elementor-control-media__preview i {
  font-size: 70px;
  color: #000000;
}
```
