### ISSUE TITLE
Make Media Carousel widget more mobile friendly

### ISSUE THREAD

**Issue by drawcard** [elementor/elementor#9128]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

Media Carousel widget doesn't display on-hover text for mobiles, making it difficult to view the descriptive text for the carousel. Some sort of CSS like this, to toggle on and off, would be handy.

The issue described in #1922 can also be fixed with similar means. 

```css
@media only screen and (max-width: 768px) {
    selector .elementor-carousel-image-overlay {
    opacity: 0.75;
    height: auto;
    top: auto;
    bottom: 0px;
}
}

```

Result:

![image](https://user-images.githubusercontent.com/1435638/65216969-d1012f00-daf1-11e9-920b-7035f2c8655a.png)
