### ISSUE TITLE
CSS Attribute Selecors not supported

### ISSUE THREAD

**Issue by shirokoweb** [elementor/elementor#9279]
- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest stable version of Elementor.

## Description

Styling posts badges using CSS Attribute selectors doesn't work.

This works :

```css
.custom_taxonomy-what-ever-category-name .elementor-post__badge {
    background: red !important;
}
```

While this doesn't :

```css
[class^="custom_taxonomy"] .elementor-post__badge {
    background: red !important;
}
```

## Steps to reproduce

Create a CPT (tour_categories) and Custom taxonomy (destinations).
Add some destinations to Tour categories (Asia, Afrika, Europe, USA...) which gives your CSS classes like :

.tour_categories-afrika
.tour_categories-asia
etc.

Target classes with CSS Attribute selector as described in "description" above won't work.
Add FULL class name works....

## Isolating the problem

- [ X ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ X ] This bug happens with a default WordPress theme active.
- [ X ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | LiteSpeed |  
MySQL version: | MariaDB Server v10.3.18 |  
PHP Version: | 7.3.9 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  


```
</details>
