### ISSUE TITLE
Accessibility: Skip links

### ISSUE THREAD

**Issue by swinggraphics** [elementor/elementor#9292]
- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Elementor should include a "Skip to main content" link by default for pages it completely takes over (where the theme doesn't get a chance to include its own). Ideally, there would also be a way to customize these links.

**Comment by shilo-ey** [comment]
Hi @swinggraphics 

Thanks for your feedback.

When using Elementor pages and templates, you can add this feature to the pages markdown with custom HTML widget inside your header/footer/template:

```HTML            
<a class="skip-main" href="#main" tabindex="-1">Skip to main content</a>
```

and some CSS:
```CSS
a.skip-main {
    left:-999px;
    position:absolute;
    top:auto;
    width:1px;
    height:1px;
    overflow:hidden;
    z-index:-999;
}
a.skip-main:focus, a.skip-main:active {
    color: #fff;
    background-color:#000;
    left: auto;
    top: auto;
    width: 30%;
    height: auto;
    overflow:auto;
    margin: 10px 35%;
    padding:5px;
    border-radius: 15px;
    border:4px solid yellow;
    text-align:center;
    font-size:1.2em;
    z-index:999;
}
```

ref: https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/mouse-and-keyboard-events/skip-to-main-content/#content

Elementor provides the markup generation, but this accessibility feature can be added quite easily.

Thanks
